# Generated by Django 4.2.7 on 2023-11-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Data', 'verbose_name_plural': 'User Data'},
        ),
    ]
