# Generated by Django 4.2.7 on 2023-12-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/Default.jpg', upload_to='images/%Y/%m', verbose_name='user_pic'),
        ),
    ]
