# Generated by Django 4.2.7 on 2023-12-08 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='category name')),
                ('desc', models.TextField(blank=True, default='', max_length=200, verbose_name='category description')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='creating date')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
            ],
            options={
                'verbose_name': 'blog category',
                'verbose_name_plural': 'blog category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name="post's tag")),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='creating date')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
            ],
            options={
                'verbose_name': "post's tag",
                'verbose_name_plural': "post's tag",
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=61, verbose_name='Title')),
                ('desc', models.TextField(blank=True, default='', max_length=200, verbose_name='Description')),
                ('content', models.TextField(verbose_name='Details')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='creating date')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('tags', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.tag', verbose_name="post's tag")),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'post',
            },
        ),
    ]
