# Generated by Django 4.2.7 on 2023-12-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_tag_options_post_category_alter_post_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Module name')),
                ('display_type', models.PositiveIntegerField(choices=[(1, 'Search'), (2, 'Latest post'), (3, 'Most popular post'), (4, 'Latest comment'), (5, 'Post archive'), (6, 'HTML')], default=1, verbose_name='Display type')),
                ('content', models.CharField(blank=True, default='', help_text='If the setting is not HTML type, it can be empty', max_length=500, verbose_name='Content')),
                ('sort', models.PositiveIntegerField(default=1, help_text='The larger the serial number, the higher the order.', verbose_name='Sort')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Hide'), (2, 'Show')], default=2, verbose_name='Status')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
            ],
            options={
                'verbose_name': 'Sidebar',
                'verbose_name_plural': 'Sidebar',
                'ordering': ['-sort'],
            },
        ),
    ]
