# Generated by Django 4.2.7 on 2023-12-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sidebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, 'Search'), (2, 'New post'), (3, 'Hot post'), (4, 'Latest comment'), (5, 'Post archives'), (6, 'HTML')], default=1, verbose_name='Display type'),
        ),
    ]
