# Generated by Django 4.2.7 on 2023-12-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_sidebar_display_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='pv',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
    ]
