# Generated by Django 4.2.7 on 2023-12-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_sidebar_pv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebar',
            name='pv',
        ),
        migrations.AddField(
            model_name='post',
            name='pv',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
    ]
