# Generated by Django 4.2.7 on 2023-12-12 19:58

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_sidebar_pv_post_pv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='Content'),
        ),
    ]
